Fix failing build on Fedora 31 with Java 11
SWT 4.6 made tests crash for me when run on Fedora 31 (Gtk 3.24).
Running with Java 11 means javax.annotation is not available.
This all ends up with:
!ENTRY org.eclipse.swt.cocoa.macosx.x86_64 2 0 2020-02-04 09:30:32.578
!MESSAGE Could not resolve module: org.eclipse.swt.cocoa.macosx.x86_64
[94]
  Unresolved requirement: Require-Capability: eclipse.platform;
filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"


!ENTRY org.eclipse.swt.win32.win32.x86_64 2 0 2020-02-04 09:30:32.579
!MESSAGE Could not resolve module: org.eclipse.swt.win32.win32.x86_64
[93]
  Unresolved requirement: Require-Capability: eclipse.platform;
filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86_64))"


!ENTRY org.eclipse.osgi 4 0 2020-02-04 09:30:32.579
!MESSAGE Application error
!STACK 1
org.eclipse.e4.core.di.InjectionException:
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)

Fixing it was just a matter of moving to Eclipse 4.14 in the
targetplatform.



Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>